/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShuttleFilterDrawer: typeof import('./src/components/ShuttleFilterDrawer.vue')['default']
    ShuttleFilterToggle: typeof import('./src/components/ShuttleFilterToggle.vue')['default']
    ShuttleTitle: typeof import('./src/components/ShuttleTitle.vue')['default']
  }
}
